#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/prezto/zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    if command mkdir "${zcompdump}.zwc.lock" 2>/dev/null; then
      zcompile "$zcompdump"
      command rmdir  "${zcompdump}.zwc.lock" 2>/dev/null
    fi
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
if [[ -o INTERACTIVE && -t 2 ]]; then

  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    fortune -s
    print
  fi

fi >&2

# Refresh SSH_AUTH_SOCK for tmux session
{
  agent="$HOME/.ssh/agent"
  if [ -S "$SSH_AUTH_SOCK" ]; then
      case $SSH_AUTH_SOCK in
      /tmp/*/agent.[0-9]*)
          ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
      esac
  elif [ -S $agent ]; then
      export SSH_AUTH_SOCK=$agent
  fi
}
