# -*- mode: shellscript -*-

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

function path-append() {
  for ARG in "$@"; do
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
      PATH="${PATH:+"$PATH:"}$ARG"
    fi
  done
}

function path-prepend() {
  for ARG in "$@"; do
    if [ -d "$ARG" ] && [[ ":$PATH:" != *":$ARG:"* ]]; then
      PATH="$ARG${PATH:+":$PATH"}"
    fi
  done
}

if [ -f "$HOME/.config/zsh/private.zshrc.zsh" ]; then
  source "$HOME/.config/zsh/private.zshrc.zsh"
fi

#
# zsh
#

setopt CLOBBER
setopt HIST_FCNTL_LOCK
setopt INC_APPEND_HISTORY
unsetopt AUTO_CD
unsetopt CDABLE_VARS
unsetopt CORRECT
unsetopt EXTENDED_GLOB

#
# Aliases
#

if [ $(uname) = 'Linux' ]; then
  alias ls='ls -F --color=auto'
else
  alias ls='ls -FG'
fi

#
# Environment variables
#

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export WORDCHARS=''
export EDITOR=vi
export VISUAL=vi
# Remove following arguments from default `LESS`
# - -F (--quit-if-one-screen)
# - -g (--hilite-search)
# - -S (--chop-long-lines)
# - -w (--hilite-unread)
export LESS='-i -M -R -X -z-4'

# HISTORY_IGNORE='(cat *|cd|cd *|make *|mv *|less *|ls|ls *|ps|ps *|pwd|rm *|tmux|make)'

export PATH="$HOME/opt/bin:$PATH:/usr/sbin:/sbin"
# /opt/go
export GOPATH="$HOME/opt/go"
export PATH="$HOME/opt/go/bin:$PATH"
# /opt/node
export PATH="$HOME/opt/node/bin:$PATH"
# /opt/ruby
export GEM_HOME="$HOME/opt/ruby/gems"
export PATH="$HOME/opt/ruby/gems/bin:$PATH"
# /opt/php
export COMPOSER_HOME="$HOME/opt/php/composer"
export PATH="$HOME/opt/php/bin:$PATH"
export PATH="$HOME/opt/php/composer/vendor/bin:$PATH"
# /opt/python
export PYTHONUSERBASE="$HOME/opt/python"
export PATH="$HOME/opt/python/bin:$PATH"

#
# Hook
#

function my-widget-set-window-title() {
  # Truncate %d to 25 character
  set-window-title "%20>...>$ZSH_PROMPT_HOSTNAME" "%25<...<%d"
}
add-zsh-hook chpwd my-widget-set-window-title
add-zsh-hook precmd my-widget-set-window-title

#
# Key bindings
#

bindkey '^U' backward-kill-line

function my-widget-cdup() {
  cd ..
  prompt_${prompt_theme}_precmd
  zle reset-prompt
  return 0
}
zle -N my-widget-cdup
bindkey '^q' my-widget-cdup

function my-widget-popd() {
  popd
  prompt_${prompt_theme}_precmd
  zle reset-prompt
  return 0
}
zle -N my-widget-popd
bindkey '^o' my-widget-popd

function my-widget-peco-select-history() {
  typeset tac
  if which tac >/dev/null; then
    tac=tac
  else
    tac='tail -r'
  fi
  BUFFER=$(fc -l -n 1 | eval $tac | peco --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle -R -c
}
zle -N my-widget-peco-select-history
bindkey '^r' my-widget-peco-select-history

#
# External tools
#

if is-callable 'direnv'; then
  eval "$(direnv hook zsh)"
fi
